---
project_name: tiledash
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tiledash
    main: ./main.go
    binary: tiledash
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}
      - -X main.Commit={{ .FullCommit }}

dockers_v2:
  - id: tiledash
    ids:
      - tiledash
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.description: "Create custom dashboards from a API returning JSON data"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.source: "https://github.com/gi8lino/tiledash"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.url: "https://github.com/gi8lino/tiledash"
      org.opencontainers.image.version: "{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    images:
      - ghcr.io/gi8lino/tiledash
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
